import { Album } from "./Album";
import { TAGS } from "./Tags";

export const albumsDatabase: Album[] = [
  {
    id: 1,
    artist: "Deep Purple",
    title: "Made in Japan",
    year: 1972,
    tags: [TAGS[2], TAGS[4]],
    coverUrl: "34tawd",
    spotifyUrl: "4Ju17mkQ4MUnQWBg9auMvk",
  },
  {
    id: 2,
    artist: "Tool",
    title: "Undertow",
    year: 1993,
    tags: [TAGS[2], TAGS[3]],
    coverUrl: "u3clfk",
    spotifyUrl: "3Esn6LoXuWtLZNYq8FCzr0",
  },
  {
    id: 3,
    artist: "Faith No More",
    title: "Angel Dust",
    year: 1992,
    tags: [TAGS[2]],
    coverUrl: "av345b",
    spotifyUrl: "59GwovfBk0Kp2HJw1G7E5Q",
  },
  {
    id: 4,
    artist: "Coma",
    title: "Pierwsze Wyjście z Mroku",
    year: 2004,
    tags: [TAGS[2], TAGS[5]],
    coverUrl: "zs3kaj",
    spotifyUrl: "1T92zoilK8o5NP5GD6C7WX",
  },
  {
    id: 5,
    artist: "Coma",
    title: "Zaprzepaszczone Siły Wielkiej Armii Świętych Znaków",
    year: 2006,
    tags: [TAGS[2], TAGS[5]],
    coverUrl: "hje245",
    spotifyUrl: "4Y25amnFEzgbmBQQ98YqAm",
  },
  {
    id: 6,
    artist: "Nightwish",
    title: "Highest Hopes: The Best of Nightwish",
    year: 2005,
    tags: [TAGS[2], TAGS[5]],
    coverUrl: "lvj4vn",
    spotifyUrl: "2wbXOTQaDS9Jnu2bjpHwEd",
  },
  {
    id: 7,
    artist: "Red Hot Chili Peppers",
    title: "Freaky Styley",
    year: 1985,
    tags: [TAGS[2], TAGS[5]],
    coverUrl: "ow1pre",
    spotifyUrl: "10Oqhoq2akSJnurJOPk8xT",
  },
  {
    id: 8,
    artist: "Soundgarden",
    title: "Down on the Upside",
    year: 1996,
    tags: [TAGS[2], TAGS[5]],
    coverUrl: "c3lnem",
    spotifyUrl: "1IVa98im1RfxYp6qeOIg2B",
  },
  {
    id: 9,
    artist: "The Mars Volta",
    title: "Octahedron",
    year: 2009,
    tags: [TAGS[2]],
    coverUrl: "ptrgah",
    spotifyUrl: "63XTF7poLIFIP9YA8XVnET",
  },
  {
    id: 10,
    artist: "Guns N' Roses",
    title: "Chinese Democracy",
    year: 2008,
    tags: [TAGS[2], TAGS[5]],
    coverUrl: "llyuo6",
    spotifyUrl: "0suNLpB9xraAv1FcdlITjQ",
  },
  {
    id: 11,
    artist: "Don Broco",
    title: "Automatic",
    year: 2015,
    tags: [TAGS[2], TAGS[6]],
    coverUrl: "a04pyy",
    spotifyUrl: "4XC0gFgH9EqXlh6IcdXOZw",
  },
  {
    id: 12,
    artist: "Soundgarden",
    title: "King Animal",
    year: 2012,
    tags: [TAGS[2], TAGS[5]],
    coverUrl: "oiajsv",
    spotifyUrl: "65XXZG2pFzK99xeOuVLHP2",
  },
  {
    id: 13,
    artist: "I Am Giant",
    title: "Science and survival",
    year: 2014,
    tags: [TAGS[2], TAGS[6]],
    coverUrl: "8ay3s3",
    spotifyUrl: "1764NzFhMGckdltRzPNiRj",
  },
  {
    id: 14,
    artist: "Don Broco",
    title: "Technology",
    year: 2018,
    tags: [TAGS[2], TAGS[6]],
    coverUrl: "tc4276",
    spotifyUrl: "0R3iUk31drnPKGCdb35Cbw",
  },
  {
    id: 15,
    artist: "Alice In chains",
    title: "Facelift",
    year: 1990,
    tags: [TAGS[2], TAGS[3]],
    coverUrl: "62q0iu",
    spotifyUrl: "5LbHbwejgZXRZAgzVAjkhj",
  },
  {
    id: 16,
    artist: "Alice In Chains",
    title: "Dirt",
    year: 1992,
    tags: [TAGS[2], TAGS[3]],
    coverUrl: "dbeh6w",
    spotifyUrl: "58NXIEYqmq5dQHg9nV9duM",
  },
  {
    id: 17,
    artist: "Alice In Chains",
    title: "Jar of Flies",
    year: 1994,
    tags: [TAGS[2], TAGS[3]],
    coverUrl: "92penx",
    spotifyUrl: "4FCoFSNIFhK36holxHWCnc",
  },
  {
    id: 18,
    artist: "Audioslave",
    title: "Audioslave",
    year: 2002,
    tags: [TAGS[2], TAGS[4]],
    coverUrl: "0pm7de",
    spotifyUrl: "78guAsers0klWl6RwzgDLd",
  },
  {
    id: 19,
    artist: "Audioslave",
    title: "Out of Exile",
    year: 2005,
    tags: [TAGS[2], TAGS[4]],
    coverUrl: "1eng8t",
    spotifyUrl: "0HQhToIjonHnJRRPN4jeJU",
  },
  {
    id: 20,
    artist: "Audioslave",
    title: "Revelations",
    year: 2006,
    tags: [TAGS[2], TAGS[4]],
    coverUrl: "1fzw5y",
    spotifyUrl: "76fYJtMmnPTOpipCoH1Mgo",
  },
  {
    id: 21,
    artist: "Faith No More",
    title: "Introduce Yourself",
    year: 1987,
    tags: [TAGS[2]],
    coverUrl: "0k7mv2",
    spotifyUrl: "0kBy2KA6BuCWveFo88VmMX",
  },
  {
    id: 22,
    artist: "Faith No More",
    title: "Album of the Year",
    year: 1997,
    tags: [TAGS[2]],
    coverUrl: "mfwusj",
    spotifyUrl: "15eiCGvldXlDbIz9ZQLmw6",
  },
  {
    id: 23,
    artist: "Pearl Jam",
    title: "Ten",
    year: 1990,
    tags: [TAGS[2], TAGS[3]],
    coverUrl: "ux3vun",
    spotifyUrl: "5B4PYA7wNN4WdEXdIJu58a",
  },
  {
    id: 24,
    artist: "Porter Band",
    title: "Helicopters",
    year: 1980,
    tags: [TAGS[1], TAGS[2], TAGS[3]],
    coverUrl: "tm0h1p",
    spotifyUrl: null,
  },
  {
    id: 25,
    artist: "Soundgarden",
    title: "Superunknown",
    year: 1994,
    tags: [TAGS[2]],
    coverUrl: "ndoa1y",
    spotifyUrl: "1xHWwGSoF1DNE4hqgBRkJX",
  },
  {
    id: 26,
    artist: "Soundgarden",
    title: "Badmotorfinger",
    year: 1991,
    tags: [TAGS[2], TAGS[5]],
    coverUrl: "3f7n4w",
    spotifyUrl: "6AA5g730FNzwKI08H7rxBk",
  },
  {
    id: 27,
    artist: "Scorpions",
    title: "Face the Heat",
    year: 1995,
    tags: [TAGS[2], TAGS[5]],
    coverUrl: "uijzfw",
    spotifyUrl: "4PCVbeHbMHCyZS7Oxl4L31",
  },
  {
    id: 28,
    artist: "Temple of a Dog",
    title: "Temple of a Dog",
    year: 1991,
    tags: [TAGS[2], TAGS[3]],
    coverUrl: "ny4uy2",
    spotifyUrl: "63HdXCn0Xz1pRZc2GzMw7k",
  },
  {
    id: 29,
    artist: "Stone Temple Pilots",
    title: "Core",
    year: 1992,
    tags: [TAGS[2]],
    coverUrl: "nkij15",
    spotifyUrl: "7k1YOwYf369EX0aHeXApWp",
  },
  {
    id: 30,
    artist: "The Mars Volta",
    title: "Deloused in the Comatorium",
    year: 2004,
    tags: [TAGS[2]],
    coverUrl: "hnhxdx",
    spotifyUrl: "0CA2EVHhRPR5VPV78KZw89",
  },
  {
    id: 31,
    artist: "Pink Floyd",
    title: "The Dark Side of the Moon",
    year: 1973,
    tags: [TAGS[1]],
    coverUrl: null,
    spotifyUrl: "4LH4d3cOWNNsVw41Gqt2kv",
  },
  {
    id: 32,
    artist: "Pink Floyd",
    title: "Animals",
    year: 1975,
    tags: [TAGS[1]],
    coverUrl: null,
    spotifyUrl: "21jUB9RqplD6OqtsTjKBnO",
  },
  {
    id: 33,
    artist: "Pink Floyd",
    title: "Wish You Were Here",
    year: 1977,
    tags: [TAGS[1]],
    coverUrl: null,
    spotifyUrl: "6uvBKDGlJAYLH5Vy6RQVsc",
  },
  {
    id: 34,
    artist: "Pink Floyd",
    title: "The Wall",
    year: 1979,
    tags: [TAGS[1]],
    coverUrl: null,
    spotifyUrl: "6WaIQHxEHtZL0RZ62AuY0g",
  },
  {
    id: 35,
    artist: "Lower Than Atlantis",
    title: "Lower Than Atlantis",
    year: 2014,
    tags: [TAGS[7]],
    coverUrl: null,
    spotifyUrl: "6uf4FBKy6xgAW4f1GmQ04A",
  },
  {
    id: 36,
    artist: "Lower Than Atlantis",
    title: "Safe in Sound",
    year: 2017,
    tags: [TAGS[7]],
    coverUrl: null,
    spotifyUrl: "2QEGCBGVqN0WvX2wHeuwMP",
  },
];
