import { Album } from "../interfaces/Album";
import { TAGS } from "./Tags";

const albumsDatabase: Album[] = [
  {
    id: 1,
    artist: "deep purple",
    title: "made in japan",
    year: 1972,
    tags: undefined,
  },
  {
    id: 2,
    artist: "tool",
    title: "undertow",
    year: 1993,
    tags: undefined,
  },
  {
    id: 3,
    artist: "faith no more",
    title: "angel dust",
    year: 1992,
    tags: undefined,
  },
  {
    id: 4,
    artist: "coma",
    title: "pierwsze wyjście z mroku",
    year: 2004,
    tags: [TAGS[0], TAGS[2]],
  },
  {
    id: 5,
    artist: "coma",
    title: "zaprzepaszczone siły wielkiej armii świętych znaków",
    year: 2006,
    tags: [TAGS[0], TAGS[2]],
  },
  {
    id: 6,
    artist: "nightwish",
    title: "highest hopes: the best of nightwish",
    year: 2005,
    tags: [TAGS[0], TAGS[2]],
  },
  {
    id: 7,
    artist: "red hot chili peppers",
    title: "freaky styley",
    year: 1985,
    tags: [TAGS[0], TAGS[2]],
  },
  {
    id: 8,
    artist: "soundgarden",
    title: "down on the upside",
    year: 1996,
    tags: [TAGS[0], TAGS[2]],
  },
  {
    id: 9,
    artist: "the mars volta",
    title: "octahedron",
    year: 2009,
    tags: [TAGS[0], TAGS[3]],
  },
  {
    id: 10,
    artist: "guns n'roses",
    title: "chinese democracy",
    year: 2008,
    tags: [TAGS[0], TAGS[2]],
  },
  {
    id: 11,
    artist: "don broco",
    title: "automatic",
    year: 2015,
    tags: [TAGS[0], TAGS[3]],
  },
  {
    id: 12,
    artist: "soundgarden",
    title: "king animal",
    year: 2012,
    tags: [TAGS[0], TAGS[2]],
  },
  {
    id: 13,
    artist: "i am giant",
    title: "science and survival",
    year: 2014,
    tags: [TAGS[0], TAGS[3]],
  },
  {
    id: 14,
    artist: "don broco",
    title: "technology",
    year: 2018,
    tags: [TAGS[0], TAGS[3]],
  },
  {
    id: 15,
    artist: "alice in chains",
    title: "facelift",
    year: 1990,
    tags: [TAGS[0], TAGS[1]],
  },
  {
    id: 16,
    artist: "alice in chains",
    title: "dirt",
    year: 1992,
    tags: [TAGS[0], TAGS[1]],
  },
  {
    id: 17,
    artist: "alice in chains",
    title: "jar of flies",
    year: 1994,
    tags: [TAGS[0], TAGS[1]],
  },
  {
    id: 18,
    artist: "audioslave",
    title: "audioslave",
    year: 2002,
    tags: [TAGS[0]],
  },
  {
    id: 19,
    artist: "audioslave",
    title: "out of exile",
    year: 2005,
    tags: [TAGS[0]],
  },
  {
    id: 20,
    artist: "audioslave",
    title: "revelations",
    year: 2006,
    tags: [TAGS[0]],
  },
  {
    id: 21,
    artist: "faith no more",
    title: "introduce yourself",
    year: 1987,
    tags: undefined,
  },
  {
    id: 22,
    artist: "faith no more",
    title: "album of the year",
    year: 1997,
    tags: undefined,
  },
  {
    id: 23,
    artist: "pearl jam",
    title: "ten",
    year: 1990,
    tags: undefined,
  },
  {
    id: 24,
    artist: "porter band",
    title: "helicopters",
    year: 1980,
    tags: undefined,
  },
  {
    id: 25,
    artist: "soundgarden",
    title: "superunknown",
    year: 1994,
    tags: undefined,
  },
  {
    id: 26,
    artist: "soundgarden",
    title: "badmotorfinger",
    year: 1991,
    tags: undefined,
  },
  {
    id: 27,
    artist: "scorpions",
    title: "face the heat",
    year: 1995,
    tags: undefined,
  },
  {
    id: 28,
    artist: "temple of a dog",
    title: "temple of a dog",
    year: 1991,
    tags: undefined,
  },
  {
    id: 29,
    artist: "stone temple pilots",
    title: "core",
    year: 1992,
    tags: undefined,
  },
  {
    id: 30,
    artist: "the mars volta",
    title: "de-loused in the comatorium",
    year: 2004,
    tags: undefined,
  },
];

export default albumsDatabase;
