const LABELS = {
  EN: {
    ARTIST_ASCENDING: "Sort by artist name (ascending)",
    ARTIST_DESCENDING: "Sort by artist name (descending)",
    PAGE: "Page",
    PAGE_SEPARATOR: "of",
    RANDOM: "Random order",
    SEARCHBYARTIST: "Search by album artist",
    SEARCHBYTITLE: "Search by album title",
    SEARCHBYYEAR: "Search by release year",
    SORTING: "Sort by",
    TAGS: "Tags",
    TAGS_DESC: {
      0: "",
      1: "My very first contact with CDs. These are a part of my father's collection and I used to listen to them on my AIWA XP-V835 discman.",
      2: "Albums downloaded from the net.",
      3: "All the CDs owned by me 'physically'.",
      4: "CDs that I bought at an electronics store (Media Markt, Saturn).",
      5: "CDs that I was given as a gift.",
      6: "CDs that I bought at the Biedronka store.",
      7: "LPs that I bought at the Biedronka store.",
      8: "CDs that I bought online (Allegro, OLX).",
      9: "Music discovered via Spotify.",
    },
    TOTAL: "Total amount: ##COUNT## albums",
    TITLE_ASCENDING: "Sort by album title (ascending)",
    TITLE_DESCENDING: "Sort by album title (descending)",
    YEAR_ASCENDING: "Sort by year published (ascending)",
    YEAR_DESCENDING: "Sort by year published (descending)",
  },
  PL: {
    ARTIST_ASCENDING: "Sortuj wg wykonawcy (rosnąco)",
    ARTIST_DESCENDING: "Sortuj wg wykonawcy (malejąco)",
    PAGE: "Strona",
    PAGE_SEPARATOR: "z",
    RANDOM: "Losowa kolejność",
    SEARCHBYARTIST: "Szukaj po wykonawcy albumu",
    SEARCHBYTITLE: "Szukaj po nazwie albumu",
    SEARCHBYYEAR: "Szukaj po roku wydania",
    SORTING: "Sortuj",
    TAGS: "Tagi",
    TAGS_DESC: {
      0: "",
      1: "Pierwszy kontakt z płytami CD (kolekcja ojca). Słuchane na discmanie AIWA XP-V835 kupionym za pierwsze zarobione pieniądze.",
      2: "Era pobierania albumów przez internet i trzymania ich na dysku twardym.",
      3: "Wszystkie posiadane przeze mnie płyty CD.",
      4: "Płyty CD zakupione w sklepie z elektroniką (Media Markt, Saturn).",
      5: "Płyty CD otrzymane w prezencie.",
      6: "Płyty CD zakupione w Biedronce (za 19,99 zł).",
      7: "Płyty winylowe zakupione w Biedronce (za 49,99 zł).",
      8: "Płyty CD zakupione przez internet (Allegro, OLX).",
      9: "Albumy odkryte dzięki Spotify.",
    },
    TOTAL: "Znaleziono ##COUNT## albumów",
    TITLE_ASCENDING: "Sortuj wg nazwy albumu (rosnąco)",
    TITLE_DESCENDING: "Sortuj wg nazwy albumu (malejąco)",
    YEAR_ASCENDING: "Sortuj wg roku wydania (rosnąco)",
    YEAR_DESCENDING: "Sortuj wg roku wydania (malejąco)",
  },
};

export default LABELS.PL;
