interface Settings {
  LIGHT_THEME: boolean;
  LOADING_TIMEOUT: number;
  SEARCHBYARTIST_ONLOAD: boolean;
  SEARCHBYTITLE_ONLOAD: boolean;
  SEARCHBYYEAR_ONLOAD: boolean;
  PAGINATION_PAGESIZE: number;
}

export const SETTINGS: Settings = {
  LIGHT_THEME: false,
  LOADING_TIMEOUT: 1000,
  SEARCHBYARTIST_ONLOAD: true,
  SEARCHBYTITLE_ONLOAD: true,
  SEARCHBYYEAR_ONLOAD: true,
  PAGINATION_PAGESIZE: 10,
};
