interface Settings {
  SEARCHBYARTIST_ONLOAD: boolean;
  SEARCHBYTITLE_ONLOAD: boolean;
  SEARCHBYYEAR_ONLOAD: boolean;
  PAGINATION_PAGESIZE: number;
}

export const SETTINGS: Settings = {
  SEARCHBYARTIST_ONLOAD: true,
  SEARCHBYTITLE_ONLOAD: true,
  SEARCHBYYEAR_ONLOAD: true,
  PAGINATION_PAGESIZE: 10,
};
