import LABELS from "./Labels";

export const SORTING_OPTIONS = {
  ARTIST_ASCENDING: LABELS.ARTIST_ASCENDING,
  ARTIST_DESCENDING: LABELS.ARTIST_DESCENDING,
  TITLE_ASCENDING: LABELS.TITLE_ASCENDING,
  TITLE_DESCENDING: LABELS.TITLE_DESCENDING,
  YEAR_ASCENDING: LABELS.YEAR_ASCENDING,
  YEAR_DESCENDING: LABELS.YEAR_DESCENDING,
};
